linters:
  enable-all: true
  disable:
    - copyloopvar
    - deadcode
    - depguard
    - dupl
    - exhaustivestruct
    - gochecknoglobals
    - golint
    - ifshort
    - interfacer
    - intrange
    - lll
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - wsl
